spring:
  application:
    name: nasa-api-consumer
  output:
    ansi:
      enabled: ALWAYS
  #data base
  datasource:
    url: jdbc:mysql://localhost:3306/nasa_integration_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Configuración JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
#Nasa integration
nasa:
  api:
    base-url: ${NASA_URL}
    key: ${NASA_KEY}
#Swagger and spring doc
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
#JWT security
application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 60
      refresh-token:
        expiration: 120